import type { TileTemplate } from './types';

/**
 * All 8 slide templates in the LiveTile Design System.
 * Grid: 12 cols × 7 rows.  Each tile uses { col, row, cs (colSpan), rs (rowSpan) }.
 * Pixel-perfect copy of the canonical LiveTileLibrary template definitions.
 */
export const TEMPLATES: TileTemplate[] = [
  {
    id: 'title-overview',
    name: 'Title Overview',
    icon: '⬛',
    description: 'Hero header + 8 audit steps + metadata',
    slideTitle: 'Copilot Studio Evaluation Audit',
    slideSubtitle: 'Open workspace · Review metrics · Review results · Review responses',
    tiles: [
      { id: 'hero',  type: 'hero',           col: 1,  row: 1, cs: 12, rs: 2 },
      { id: 'cards', type: 'overview-cards',  col: 1,  row: 3, cs: 8,  rs: 5 },
      { id: 'meta',  type: 'meta-info',       col: 9,  row: 3, cs: 4,  rs: 5 },
    ],
  },
  {
    id: 'dashboard',
    name: 'Dashboard',
    icon: '▦',
    description: 'Header + KPIs + chart regions for evaluation review',
    slideTitle: 'Evaluation Review Dashboard',
    slideSubtitle: 'Native metrics · Results archive · Response evidence',
    tiles: [
      { id: 'hdr', type: 'accent-header', col: 1,  row: 1, cs: 12, rs: 1 },
      { id: 'm1',  type: 'kpi',           col: 1,  row: 2, cs: 3,  rs: 2 },
      { id: 'm2',  type: 'kpi',           col: 4,  row: 2, cs: 3,  rs: 2 },
      { id: 'm3',  type: 'kpi',           col: 7,  row: 2, cs: 3,  rs: 2 },
      { id: 'm4',  type: 'kpi',           col: 10, row: 2, cs: 3,  rs: 2 },
      { id: 'bar', type: 'bar-chart',     col: 1,  row: 4, cs: 7,  rs: 4 },
      { id: 'pie', type: 'pie-chart',     col: 8,  row: 4, cs: 5,  rs: 4 },
    ],
  },
  {
    id: 'analytics',
    name: 'Analytics',
    icon: 'CHART',
    description: 'Line trend + radar + stacked bar',
    slideTitle: 'Evaluation Metrics and Response Signals',
    slideSubtitle: 'Quality trend · Pass rate · Trace coverage',
    tiles: [
      { id: 'hdr',     type: 'accent-header', col: 1, row: 1, cs: 12, rs: 1 },
      { id: 'line',    type: 'line-chart',    col: 1, row: 2, cs: 7,  rs: 3 },
      { id: 'radar',   type: 'radar-chart',   col: 8, row: 2, cs: 5,  rs: 3 },
      { id: 'stacked', type: 'stacked-bar',   col: 1, row: 5, cs: 7,  rs: 3 },
      { id: 'stats',   type: 'stat-block',    col: 8, row: 5, cs: 5,  rs: 3 },
    ],
  },
  {
    id: 'comparison',
    name: 'Comparison',
    icon: '⊞',
    description: 'Side-by-side two-column comparison',
    slideTitle: 'Offline vs Online Evaluation',
    slideSubtitle: 'BIC Methodology · Pre/Post Deploy',
    tiles: [
      { id: 'hdr',   type: 'accent-header', col: 1, row: 1, cs: 12, rs: 1 },
      { id: 'left',  type: 'compare-left',  col: 1, row: 2, cs: 6,  rs: 6 },
      { id: 'right', type: 'compare-right', col: 7, row: 2, cs: 6,  rs: 6 },
    ],
  },
  {
    id: 'pipeline',
    name: 'Pipeline Flow',
    icon: '⟶',
    description: 'Workflow steps + review checklist + chart region',
    slideTitle: 'Evaluation Review Workflow',
    slideSubtitle: 'Open Studio → Metrics → Results → Responses → Evidence',
    tiles: [
      { id: 'hdr',    type: 'accent-header', col: 1, row: 1, cs: 12, rs: 1 },
      { id: 'flow',   type: 'pipeline',      col: 1, row: 2, cs: 12, rs: 2 },
      { id: 'status', type: 'status-grid',   col: 1, row: 4, cs: 5,  rs: 4 },
      { id: 'bar2',   type: 'bar-chart',     col: 6, row: 4, cs: 7,  rs: 4 },
    ],
  },
  {
    id: 'executive',
    name: 'Executive Brief',
    icon: 'BRIEF',
    description: 'Audit brief + KPIs + callout blocks',
    slideTitle: 'Evaluation Audit Brief',
    slideSubtitle: 'Copilot Studio review checklist · Current run',
    tiles: [
      { id: 'hdr',    type: 'accent-header', col: 1, row: 1, cs: 12, rs: 1 },
      { id: 'facts',  type: 'fact-sheet',    col: 1, row: 2, cs: 5,  rs: 6 },
      { id: 'kpi1',   type: 'kpi',           col: 6, row: 2, cs: 3,  rs: 2 },
      { id: 'kpi2',   type: 'kpi',           col: 9, row: 2, cs: 4,  rs: 2 },
      { id: 'em1',    type: 'emphasis',       col: 6, row: 4, cs: 7,  rs: 2 },
      { id: 'table2', type: 'table',          col: 6, row: 6, cs: 7,  rs: 2 },
    ],
  },
  {
    id: 'data-report',
    name: 'Data Report',
    icon: 'DOC',
    description: 'Step table + trend line + pie donut',
    slideTitle: 'Evaluation Audit Evidence',
    slideSubtitle: 'Steps, metrics, and response review',
    tiles: [
      { id: 'hdr',   type: 'accent-header', col: 1, row: 1, cs: 12, rs: 1 },
      { id: 'tbl',   type: 'table',         col: 1, row: 2, cs: 6,  rs: 4 },
      { id: 'line2', type: 'line-chart',     col: 7, row: 2, cs: 6,  rs: 4 },
      { id: 'pie2',  type: 'pie-chart',      col: 1, row: 6, cs: 4,  rs: 2 },
      { id: 'em2',   type: 'emphasis',        col: 5, row: 6, cs: 4,  rs: 2 },
      { id: 'kpi5',  type: 'kpi',            col: 9, row: 6, cs: 4,  rs: 2 },
    ],
  },
  {
    id: 'kpi-board',
    name: 'KPI Board',
    icon: 'KPI',
    description: 'All metrics — radar, pie, trend, KPIs',
    slideTitle: 'Evaluation Surface KPI Board',
    slideSubtitle: 'Metrics · Results · Responses · Evidence',
    tiles: [
      { id: 'hdr',    type: 'accent-header', col: 1,  row: 1, cs: 12, rs: 1 },
      { id: 'k1',     type: 'kpi',           col: 1,  row: 2, cs: 2,  rs: 2 },
      { id: 'k2',     type: 'kpi',           col: 3,  row: 2, cs: 2,  rs: 2 },
      { id: 'k3',     type: 'kpi',           col: 5,  row: 2, cs: 2,  rs: 2 },
      { id: 'k4',     type: 'kpi',           col: 7,  row: 2, cs: 2,  rs: 2 },
      { id: 'k5',     type: 'kpi',           col: 9,  row: 2, cs: 2,  rs: 2 },
      { id: 'k6',     type: 'kpi',           col: 11, row: 2, cs: 2,  rs: 2 },
      { id: 'radar2', type: 'radar-chart',   col: 1,  row: 4, cs: 5,  rs: 4 },
      { id: 'pie3',   type: 'pie-chart',     col: 6,  row: 4, cs: 4,  rs: 4 },
      { id: 'line3',  type: 'line-chart',    col: 10, row: 4, cs: 3,  rs: 4 },
    ],
  },

  // ── Agent & Bot Analytics Templates ──────────────────────────────────────

  {
    id: 'agent-analytics',
    name: 'Agent Analytics',
    icon: 'AGENT',
    description: 'Agent response quality + session KPIs + message distribution',
    slideTitle: 'Agent Performance Analytics',
    slideSubtitle: 'Response quality · Session metrics · Message routing · CSAT',
    tiles: [
      { id: 'hdr',   type: 'accent-header', col: 1,  row: 1, cs: 12, rs: 1 },
      { id: 'k1',    type: 'kpi',           col: 1,  row: 2, cs: 3,  rs: 2 },
      { id: 'k2',    type: 'kpi',           col: 4,  row: 2, cs: 3,  rs: 2 },
      { id: 'k3',    type: 'kpi',           col: 7,  row: 2, cs: 3,  rs: 2 },
      { id: 'k4',    type: 'kpi',           col: 10, row: 2, cs: 3,  rs: 2 },
      { id: 'bar',   type: 'bar-chart',     col: 1,  row: 4, cs: 7,  rs: 4 },
      { id: 'pie',   type: 'pie-chart',     col: 8,  row: 4, cs: 5,  rs: 4 },
    ],
  },
  {
    id: 'bot-dashboard',
    name: 'Bot Dashboard',
    icon: 'BOT',
    description: 'Bot operations — status grid + trend + KPIs + resolution',
    slideTitle: 'Bot Operations Dashboard',
    slideSubtitle: 'Agent health · Resolution rates · Escalation tracking · Trends',
    tiles: [
      { id: 'hdr',     type: 'accent-header', col: 1, row: 1, cs: 12, rs: 1 },
      { id: 'k1',      type: 'kpi',           col: 1, row: 2, cs: 2,  rs: 2 },
      { id: 'k2',      type: 'kpi',           col: 3, row: 2, cs: 2,  rs: 2 },
      { id: 'k3',      type: 'kpi',           col: 5, row: 2, cs: 2,  rs: 2 },
      { id: 'status',  type: 'status-grid',   col: 7, row: 2, cs: 6,  rs: 2 },
      { id: 'line',    type: 'line-chart',    col: 1, row: 4, cs: 6,  rs: 4 },
      { id: 'stacked', type: 'stacked-bar',   col: 7, row: 4, cs: 6,  rs: 4 },
    ],
  },
  {
    id: 'conversation-flow',
    name: 'Conversation Flow',
    icon: 'CONV',
    description: 'Intent routing + conversation metrics + flow pipeline',
    slideTitle: 'Conversation Flow Analytics',
    slideSubtitle: 'Intent distribution · Message routing · Resolution pipeline · Coverage',
    tiles: [
      { id: 'hdr',     type: 'accent-header', col: 1, row: 1, cs: 12, rs: 1 },
      { id: 'flow',    type: 'pipeline',      col: 1, row: 2, cs: 12, rs: 2 },
      { id: 'radar',   type: 'radar-chart',   col: 1, row: 4, cs: 4,  rs: 4 },
      { id: 'pie',     type: 'pie-chart',     col: 5, row: 4, cs: 4,  rs: 4 },
      { id: 'stats',   type: 'stat-block',    col: 9, row: 4, cs: 4,  rs: 4 },
    ],
  },

  {
    id: 'channel-analytics',
    name: 'Channel Analytics',
    icon: 'CHAN',
    description: 'Grouped column volume + KPIs + trend line + status grid',
    slideTitle: 'Channel Volume Analytics',
    slideSubtitle: 'Multi-channel volume · Trends · Fleet health · Weekly movement',
    tiles: [
      { id: 'hdr',    type: 'accent-header',   col: 1,  row: 1, cs: 12, rs: 1 },
      { id: 'k1',     type: 'kpi',             col: 1,  row: 2, cs: 3,  rs: 2 },
      { id: 'k2',     type: 'kpi',             col: 4,  row: 2, cs: 3,  rs: 2 },
      { id: 'k3',     type: 'kpi',             col: 7,  row: 2, cs: 3,  rs: 2 },
      { id: 'k4',     type: 'kpi',             col: 10, row: 2, cs: 3,  rs: 2 },
      { id: 'gcol',   type: 'grouped-column',  col: 1,  row: 4, cs: 7,  rs: 4 },
      { id: 'line',   type: 'line-chart',      col: 8,  row: 4, cs: 5,  rs: 4 },
    ],
  },
];
