import type { TileTemplate } from './types';

/**
 * Slide templates in the LiveTile Design System.
 * Grid: 12 cols × 7 rows.  Each tile uses { col, row, cs (colSpan), rs (rowSpan) }.
 * Pixel-perfect copy of the canonical LiveTileLibrary template definitions.
 */
export const TEMPLATES: TileTemplate[] = [
  {
    id: 'title-overview',
    name: 'Title Overview',
    icon: 'OVR',
    description: 'Hero header, capability cards, and metadata',
    slideTitle: 'Healthcare Access Program',
    slideSubtitle: 'Patient intake, care navigation, service quality, and outcomes',
    tiles: [
      { id: 'hero',  type: 'hero',           col: 1,  row: 1, cs: 12, rs: 2 },
      { id: 'cards', type: 'overview-cards',  col: 1,  row: 3, cs: 8,  rs: 5 },
      { id: 'meta',  type: 'meta-info',       col: 9,  row: 3, cs: 4,  rs: 5 },
    ],
  },
  {
    id: 'dashboard',
    name: 'Dashboard',
    icon: 'DASH',
    description: 'Header, KPIs, and chart regions for an operating review',
    slideTitle: 'Financial Services Portfolio Dashboard',
    slideSubtitle: 'Risk posture, service levels, client impact, and operations',
    tiles: [
      { id: 'hdr', type: 'accent-header', col: 1,  row: 1, cs: 12, rs: 1 },
      { id: 'm1',  type: 'kpi',           col: 1,  row: 2, cs: 3,  rs: 2 },
      { id: 'm2',  type: 'kpi',           col: 4,  row: 2, cs: 3,  rs: 2 },
      { id: 'm3',  type: 'kpi',           col: 7,  row: 2, cs: 3,  rs: 2 },
      { id: 'm4',  type: 'kpi',           col: 10, row: 2, cs: 3,  rs: 2 },
      { id: 'bar', type: 'bar-chart',     col: 1,  row: 4, cs: 7,  rs: 4 },
      { id: 'pie', type: 'pie-chart',     col: 8,  row: 4, cs: 5,  rs: 4 },
    ],
  },
  {
    id: 'analytics',
    name: 'Analytics',
    icon: 'ANLY',
    description: 'Line trend, radar chart, stacked bar, and movement summary',
    slideTitle: 'Retail Demand and Experience Analytics',
    slideSubtitle: 'Demand trend, channel mix, loyalty signals, and conversion',
    tiles: [
      { id: 'hdr',     type: 'accent-header', col: 1, row: 1, cs: 12, rs: 1 },
      { id: 'line',    type: 'line-chart',    col: 1, row: 2, cs: 7,  rs: 3 },
      { id: 'radar',   type: 'radar-chart',   col: 8, row: 2, cs: 5,  rs: 3 },
      { id: 'stacked', type: 'stacked-bar',   col: 1, row: 5, cs: 7,  rs: 3 },
      { id: 'stats',   type: 'stat-block',    col: 8, row: 5, cs: 5,  rs: 3 },
    ],
  },
  {
    id: 'comparison',
    name: 'Comparison',
    icon: 'COMP',
    description: 'Side-by-side two-column comparison',
    slideTitle: 'Manufacturing Quality Strategy',
    slideSubtitle: 'Preventive controls, inspection flow, throughput, and defects',
    tiles: [
      { id: 'hdr',   type: 'accent-header', col: 1, row: 1, cs: 12, rs: 1 },
      { id: 'left',  type: 'compare-left',  col: 1, row: 2, cs: 6,  rs: 6 },
      { id: 'right', type: 'compare-right', col: 7, row: 2, cs: 6,  rs: 6 },
    ],
  },
  {
    id: 'pipeline',
    name: 'Pipeline Flow',
    icon: 'FLOW',
    description: 'Workflow steps, status checklist, and chart region',
    slideTitle: 'Supply Chain Recovery Workflow',
    slideSubtitle: 'Plan, source, make, deliver, resolve, and improve',
    tiles: [
      { id: 'hdr',    type: 'accent-header', col: 1, row: 1, cs: 12, rs: 1 },
      { id: 'flow',   type: 'pipeline',      col: 1, row: 2, cs: 12, rs: 2 },
      { id: 'status', type: 'status-grid',   col: 1, row: 4, cs: 5,  rs: 4 },
      { id: 'bar2',   type: 'bar-chart',     col: 6, row: 4, cs: 7,  rs: 4 },
    ],
  },
  {
    id: 'executive',
    name: 'Executive Brief',
    icon: 'BRIEF',
    description: 'Executive brief, KPIs, callout blocks, and action table',
    slideTitle: 'Cybersecurity Executive Brief',
    slideSubtitle: 'Risk reduction, response readiness, exposure, and controls',
    tiles: [
      { id: 'hdr',    type: 'accent-header', col: 1, row: 1, cs: 12, rs: 1 },
      { id: 'facts',  type: 'fact-sheet',    col: 1, row: 2, cs: 5,  rs: 6 },
      { id: 'kpi1',   type: 'kpi',           col: 6, row: 2, cs: 3,  rs: 2 },
      { id: 'kpi2',   type: 'kpi',           col: 9, row: 2, cs: 4,  rs: 2 },
      { id: 'em1',    type: 'emphasis',       col: 6, row: 4, cs: 7,  rs: 2 },
      { id: 'table2', type: 'table',          col: 6, row: 6, cs: 7,  rs: 2 },
    ],
  },
  {
    id: 'data-report',
    name: 'Data Report',
    icon: 'DOC',
    description: 'Data table, trend line, pie chart, callout, and KPI',
    slideTitle: 'Education Program Evidence',
    slideSubtitle: 'Learner engagement, intervention quality, and completion',
    tiles: [
      { id: 'hdr',   type: 'accent-header', col: 1, row: 1, cs: 12, rs: 1 },
      { id: 'tbl',   type: 'table',         col: 1, row: 2, cs: 6,  rs: 4 },
      { id: 'line2', type: 'line-chart',     col: 7, row: 2, cs: 6,  rs: 4 },
      { id: 'pie2',  type: 'pie-chart',      col: 1, row: 6, cs: 4,  rs: 2 },
      { id: 'em2',   type: 'emphasis',        col: 5, row: 6, cs: 4,  rs: 2 },
      { id: 'kpi5',  type: 'kpi',            col: 9, row: 6, cs: 4,  rs: 2 },
    ],
  },
  {
    id: 'kpi-board',
    name: 'KPI Board',
    icon: 'KPI',
    description: 'Dense metric board with KPIs, radar, pie, and trend',
    slideTitle: 'Energy Operations KPI Board',
    slideSubtitle: 'Reliability, safety, field response, and sustainability',
    tiles: [
      { id: 'hdr',    type: 'accent-header', col: 1,  row: 1, cs: 12, rs: 1 },
      { id: 'k1',     type: 'kpi',           col: 1,  row: 2, cs: 2,  rs: 2 },
      { id: 'k2',     type: 'kpi',           col: 3,  row: 2, cs: 2,  rs: 2 },
      { id: 'k3',     type: 'kpi',           col: 5,  row: 2, cs: 2,  rs: 2 },
      { id: 'k4',     type: 'kpi',           col: 7,  row: 2, cs: 2,  rs: 2 },
      { id: 'k5',     type: 'kpi',           col: 9,  row: 2, cs: 2,  rs: 2 },
      { id: 'k6',     type: 'kpi',           col: 11, row: 2, cs: 2,  rs: 2 },
      { id: 'radar2', type: 'radar-chart',   col: 1,  row: 4, cs: 5,  rs: 4 },
      { id: 'pie3',   type: 'pie-chart',     col: 6,  row: 4, cs: 4,  rs: 4 },
      { id: 'line3',  type: 'line-chart',    col: 10, row: 4, cs: 3,  rs: 4 },
    ],
  },

  // Industry and specialty templates.

  {
    id: 'agent-analytics',
    name: 'Customer Success',
    icon: 'CS',
    description: 'Success score, adoption KPIs, engagement mix, and segment quality',
    slideTitle: 'Customer Success Analytics',
    slideSubtitle: 'Adoption, retention, support quality, and expansion signals',
    tiles: [
      { id: 'hdr',   type: 'accent-header', col: 1,  row: 1, cs: 12, rs: 1 },
      { id: 'k1',    type: 'kpi',           col: 1,  row: 2, cs: 3,  rs: 2 },
      { id: 'k2',    type: 'kpi',           col: 4,  row: 2, cs: 3,  rs: 2 },
      { id: 'k3',    type: 'kpi',           col: 7,  row: 2, cs: 3,  rs: 2 },
      { id: 'k4',    type: 'kpi',           col: 10, row: 2, cs: 3,  rs: 2 },
      { id: 'bar',   type: 'bar-chart',     col: 1,  row: 4, cs: 7,  rs: 4 },
      { id: 'pie',   type: 'pie-chart',     col: 8,  row: 4, cs: 5,  rs: 4 },
    ],
  },
  {
    id: 'bot-dashboard',
    name: 'Public Sector',
    icon: 'GOV',
    description: 'Service status grid, trend, KPIs, and resolution outcomes',
    slideTitle: 'Public Sector Service Dashboard',
    slideSubtitle: 'Case volume, response timeliness, channel demand, and outcomes',
    tiles: [
      { id: 'hdr',     type: 'accent-header', col: 1, row: 1, cs: 12, rs: 1 },
      { id: 'k1',      type: 'kpi',           col: 1, row: 2, cs: 2,  rs: 2 },
      { id: 'k2',      type: 'kpi',           col: 3, row: 2, cs: 2,  rs: 2 },
      { id: 'k3',      type: 'kpi',           col: 5, row: 2, cs: 2,  rs: 2 },
      { id: 'status',  type: 'status-grid',   col: 7, row: 2, cs: 6,  rs: 2 },
      { id: 'line',    type: 'line-chart',    col: 1, row: 4, cs: 6,  rs: 4 },
      { id: 'stacked', type: 'stacked-bar',   col: 7, row: 4, cs: 6,  rs: 4 },
    ],
  },
  {
    id: 'conversation-flow',
    name: 'Legal Ops Flow',
    icon: 'LAW',
    description: 'Matter routing, review metrics, and flow pipeline',
    slideTitle: 'Legal Operations Matter Flow',
    slideSubtitle: 'Matter intake, review routing, evidence readiness, and closeout',
    tiles: [
      { id: 'hdr',     type: 'accent-header', col: 1, row: 1, cs: 12, rs: 1 },
      { id: 'flow',    type: 'pipeline',      col: 1, row: 2, cs: 12, rs: 2 },
      { id: 'radar',   type: 'radar-chart',   col: 1, row: 4, cs: 4,  rs: 4 },
      { id: 'pie',     type: 'pie-chart',     col: 5, row: 4, cs: 4,  rs: 4 },
      { id: 'stats',   type: 'stat-block',    col: 9, row: 4, cs: 4,  rs: 4 },
    ],
  },

  {
    id: 'channel-analytics',
    name: 'Field Services',
    icon: 'FIELD',
    description: 'Grouped column volume, KPIs, trend line, and operating status',
    slideTitle: 'Field Services Channel Analytics',
    slideSubtitle: 'Dispatch volume, technician capacity, parts availability, and SLA trend',
    tiles: [
      { id: 'hdr',    type: 'accent-header',   col: 1,  row: 1, cs: 12, rs: 1 },
      { id: 'k1',     type: 'kpi',             col: 1,  row: 2, cs: 3,  rs: 2 },
      { id: 'k2',     type: 'kpi',             col: 4,  row: 2, cs: 3,  rs: 2 },
      { id: 'k3',     type: 'kpi',             col: 7,  row: 2, cs: 3,  rs: 2 },
      { id: 'k4',     type: 'kpi',             col: 10, row: 2, cs: 3,  rs: 2 },
      { id: 'gcol',   type: 'grouped-column',  col: 1,  row: 4, cs: 7,  rs: 4 },
      { id: 'line',   type: 'line-chart',      col: 8,  row: 4, cs: 5,  rs: 4 },
    ],
  },
];
